server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    
    absolute_redirect off;

    index index.html index.csr.html;

    location / {
        try_files $uri $uri/ /index.csr.html;
    }
}